name: CI/CD for Next.js

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install

      - name: Build Next.js project
        run: |
          npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Debug
        run: ls -R

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Next.js project
        run: |
          npm run build

      - name: Debug
        run: ls -R

      - name: Set up FTP deployment
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ~/public_html/nurulbambang.my.id/
          local-dir: out/  # Assuming Next.js generated static files are in the 'out' directory 
